import os
import json
import urllib.request
import urllib.error
import sys
from core.logger import get_logger
from core.custom_exception import CustomException
from core.decorators import with_logging_and_exceptions

logger = get_logger(__name__)

# Local model configuration

# Try to import llama_cpp, but don't crash if it is not installed or fails to load DLLs
try:
    from llama_cpp import Llama
    LLAMA_CPP_AVAILABLE = True
    LLAMA_CPP_ERROR = None
except Exception as e:
    LLAMA_CPP_AVAILABLE = False
    LLAMA_CPP_ERROR = str(e)

class LocalLLMClient:
    def __init__(self, model_path="models/Qwen2.5-7B-Instruct-Q4_K_M.gguf"):
        self.model_path = model_path
        self.llm = None

    def load_model(self):
        """Loads the GGUF model into VRAM/RAM if not already loaded."""
        try:
            if not LLAMA_CPP_AVAILABLE:
                raise RuntimeError(
                    f"llama_cpp is not available or failed to load on this system: {LLAMA_CPP_ERROR}. "
                    f"Please ensure C++ build tools are installed or configure the Groq API key."
                )
            if self.llm is None:
                if not os.path.exists(self.model_path):
                    raise FileNotFoundError(
                        f"Local GGUF model not found at {self.model_path}. "
                        f"Please verify it was downloaded successfully."
                    )

                # Configure GPU offload (20 layers) to leave VRAM headroom and prevent memory corruption on 4GB GPUs
                self.llm = Llama(
                    model_path=self.model_path,
                    n_ctx=4096,          # Model native context limit
                    n_gpu_layers=-1,     # Offload all layers to GPU
                    use_mlock=False,
                    verbose=False
                )
                logger.info(f"Local GGUF model loaded from {self.model_path} on GPU.")
            return self.llm
        except Exception as e:
            logger.error(f"Failed to load local GGUF model: {e}")
            raise CustomException(e, sys)

    def generate_summary(self, prompt, max_tokens=150):
        """Generates a synchronous summary (used in ingestion/ETL)."""
        try:
            self.load_model()
            is_qwen = "qwen" in self.model_path.lower()
            if is_qwen:
                prompt = prompt.replace("<|system|>", "<|im_start|>system")
                prompt = prompt.replace("<|user|>", "<|im_start|>user")
                prompt = prompt.replace("<|assistant|>", "<|im_start|>assistant")
                prompt = prompt.replace("<|end|>", "<|im_end|>")
                if len(prompt) > 14000:
                    prompt = prompt[:14000] + "\n<|im_end|>\n<|im_start|>assistant\n"
                stop_tokens = ["\n", "Summary:", "Issue:", "<|im_end|>", "<|im_start|>"]
            else:
                if len(prompt) > 14000:
                    prompt = prompt[:14000] + "\n<|end|>\n<|assistant|>\n"
                stop_tokens = ["\n", "Summary:", "Issue:", "<|end|>", "<|user|>"]

            response = self.llm(
                prompt,
                max_tokens=max_tokens,
                temperature=0.1,
                stop=stop_tokens,
                echo=False
            )
            text = response["choices"][0]["text"].strip()
            return text
        except Exception as e:
            logger.error(f"Local LLM summary generation failed: {e}")
            raise CustomException(e, sys)

    def generate_chat_stream(self, messages):
        """
        Generates a streaming response for Streamlit chat.
        Yields tokens/chunks as they are generated by the model.
        """
        try:
            self.load_model()

            # Chat template (ignoring previous chat history to speed up inference)
            filtered_messages = []
            for msg in messages[:-1]:
                if msg["role"] == "system":
                    filtered_messages.append(msg)
            if messages:
                filtered_messages.append(messages[-1])

            is_qwen = "qwen" in self.model_path.lower()
            prompt_parts = []
            for msg in filtered_messages:
                role = msg["role"]
                content = msg["content"]
                
                # Truncate extremely long user content to fit within context safety limits
                if role == "user" and len(content) > 10000:
                    content = content[:10000] + "\n\n*(Context truncated to prevent context window overflow)*"
                    
                if is_qwen:
                    if role == "system":
                        prompt_parts.append(f"<|im_start|>system\n{content}<|im_end|>\n")
                    elif role == "user":
                        prompt_parts.append(f"<|im_start|>user\n{content}<|im_end|>\n")
                    elif role == "assistant":
                        prompt_parts.append(f"<|im_start|>assistant\n{content}<|im_end|>\n")
                else:
                    if role == "system":
                        prompt_parts.append(f"<|system|>\n{content}<|end|>\n")
                    elif role == "user":
                        prompt_parts.append(f"<|user|>\n{content}<|end|>\n")
                    elif role == "assistant":
                        prompt_parts.append(f"<|assistant|>\n{content}<|end|>\n")
            
            if is_qwen:
                prompt_parts.append("<|im_start|>assistant\n")
            else:
                prompt_parts.append("<|assistant|>\n")
            prompt = "".join(prompt_parts)

            # Safety: estimate token count (~4 chars per token)
            estimated_tokens = len(prompt) // 4
            model_ctx = 4096
            if estimated_tokens > model_ctx - 600:
                print(f"WARNING: Estimated prompt tokens ({estimated_tokens}) near context limit ({model_ctx}). Truncating prompt.")
                # Keep the tail end of the prompt where user/assistant messages reside
                prompt = prompt[-12000:]
                if is_qwen:
                    if "<|im_start|>system" not in prompt:
                        prompt = "<|im_start|>system\nYou are a helpful automotive engineering assistant.<|im_end|>\n" + prompt
                else:
                    if "<|system|>" not in prompt:
                        prompt = "<|system|>\nYou are a helpful automotive engineering assistant.<|end|>\n" + prompt

            # Call the raw completion endpoint with streaming
            stop_tokens = ["<|im_end|>", "<|im_start|>"] if is_qwen else ["<|end|>", "<|user|>", "<|system|>"]
            chat_completion = self.llm(
                prompt,
                max_tokens=512,
                temperature=0.0,
                stream=True,
                stop=stop_tokens
            )

            for chunk in chat_completion:
                choice = chunk["choices"][0]
                if "text" in choice:
                    yield choice["text"]
        except Exception as e:
            logger.error(f"Local LLM chat stream generation failed: {e}")
            raise CustomException(e, sys)


class LLMClient:
    def __init__(self, model_path="models/Qwen2.5-7B-Instruct-Q4_K_M.gguf"):
        self.model_path = model_path
        self.local_client = None

    @with_logging_and_exceptions
    def load_model(self):
        """Loads local model. Returns self for call compatibility."""
        if not self.local_client:
            self.local_client = LocalLLMClient(model_path=self.model_path)
        self.local_client.load_model()
        return self

    @with_logging_and_exceptions
    def __call__(self, prompt, max_tokens=256, temperature=0.0, stop=None, echo=False, stream=False):
        """Allows LLMClient to be called directly, routing to Local GGUF."""
        if not self.local_client:
            self.local_client = LocalLLMClient(model_path=self.model_path)
        llm = self.local_client.load_model()
        return llm(
            prompt,
            max_tokens=max_tokens,
            temperature=temperature,
            stop=stop,
            echo=echo,
            stream=stream
        )

    @with_logging_and_exceptions
    def generate_summary(self, prompt, max_tokens=150):
        if not self.local_client:
            self.local_client = LocalLLMClient(model_path=self.model_path)
        return self.local_client.generate_summary(prompt, max_tokens)

    @with_logging_and_exceptions
    def generate_chat_stream(self, messages):
        if not self.local_client:
            self.local_client = LocalLLMClient(model_path=self.model_path)
        yield from self.local_client.generate_chat_stream(messages)

