import os
from llama_cpp import Llama

class LocalLLMClient:
    def __init__(self, model_path="models/Phi-3-mini-4k-instruct-q4.gguf"):
        self.model_path = model_path
        self.llm = None

    def load_model(self):
        """Loads the GGUF model into VRAM/RAM if not already loaded."""
        if self.llm is None:
            if not os.path.exists(self.model_path):
                raise FileNotFoundError(
                    f"Local GGUF model not found at {self.model_path}. "
                    f"Please verify it was downloaded successfully."
                )
            
            # Load Llama with CUDA GPU acceleration
            self.llm = Llama(
                model_path=self.model_path,
                n_ctx=14096,         # Context discipline: 4096 max tokens (Phi-3 native)
                n_gpu_layers=-1,    # Offload all layers to GPU (n_gpu_layers=-1)
                use_mlock=True,     # Pin model in RAM/VRAM
                verbose=False       # Keep terminal output clean
            )
            print(f"Llama GGUF model loaded from {self.model_path} with GPU offloading.")
        return self.llm

    def generate_summary(self, prompt, max_tokens=150):
        """Generates a synchronous summary (used in ingestion/ETL)."""
        self.load_model()
        response = self.llm(
            prompt,
            max_tokens=max_tokens,
            temperature=0.1,
            stop=["\n", "Summary:", "Issue:"],
            echo=False
        )
        text = response["choices"][0]["text"].strip()
        return text

    def generate_chat_stream(self, messages):
        """
        Generates a streaming response for Streamlit chat.
        Yields tokens/chunks as they are generated by the model.
        """
        self.load_model()
        
        # Manually format messages for Phi-3 native chat template
        prompt_parts = []
        for msg in messages:
            role = msg["role"]
            content = msg["content"]
            if role == "system":
                prompt_parts.append(f"<|system|>\n{content}<|end|>")
            elif role == "user":
                prompt_parts.append(f"<|user|>\n{content}<|end|>")
            elif role == "assistant":
                prompt_parts.append(f"<|assistant|>\n{content}<|end|>")
        prompt_parts.append("<|assistant|>\n")
        prompt = "\n".join(prompt_parts)
        
        # Call the raw completion endpoint with streaming
        chat_completion = self.llm(
            prompt,
            max_tokens=300,        # Max output tokens limit
            temperature=0.1,       # Low temperature for factual output
            stream=True,
            stop=["<|end|>", "<|user|>", "<|system|>"]
        )
        
        for chunk in chat_completion:
            choice = chunk["choices"][0]
            if "text" in choice:
                yield choice["text"]
